packaging_format = 2

description.en = " AltServer for AltStore, but on YunoHost"
description.fr = "AltServer poiur AltStore, mais sur YunoHost"
id = "altserver_linux"
name = "AltServer-Linux"

version = "0.0.5~ynh1"

maintainers = ["OniriCorpe"]

[upstream]
code = "https://github.com/NyaMisty/AltServer-Linux"
license = "AGPL-3"
userdoc = "https://github.com/NyaMisty/AltServer-Linux#readme"

[integration]
architectures = ["amd64", "i586", "armv7", "arm64"]
disk = "50M"
multi_instance = false
ram.build = "300M"
ram.runtime = "50M"
yunohost = ">= 11.1.6"

[resources]

[resources.system_user]

[resources.install_dir]

[resources.apt]
packages = "libavahi-compat-libdnssd-dev, libusb-1.0-0-dev, libplist-dev, libplist++-dev, libusbmuxd-dev, libimobiledevice-dev, libavahi-client-dev, git, make, autoconf, automake, libtool-bin, pkg-config, clang"
